### PR TITLE
Raise ValueError on input arrays of length 0

### PR DESCRIPTION
**Pull request by geier**
Input of length zero used to seg fault SuperCluster.

### CODE REVIEW

**Comment by jlaine** [comment]
Hi!

Could you please provide a unit test for this?

Jeremy

**Comment by geier** [comment]
Good point, sorry about that.

**Comment by geier** [comment]
Turns out, I already had a test, just forgot to include it in the commit :( Should be included now.

**Comment by jlaine** [comment]
Thanks you Christian!

**Pull request merged**
